version: "3.9"

volumes:
  qdrant_data:

services:
  # -------- FRONTEND (SSR Node server) ----------
  frontend:
    image: rabbitly-frontend:prod           # use same tag everywhere
    container_name: frontend
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always

  # ------------- BACKEND GATEWAY ---------------
  backend-api:
    image: rabbitly-backend-api:prod
    container_name: backend-api
    build:
      context: ./backend-api
      target: prod
    ports:
      - "8000:8000"
    environment:
      AI_SERVICE_URL: http://ai-service:9000
      CODE_RUNNER_URL: http://code-runner:9100
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - ai-service
      - code-runner
      - qdrant
    restart: always

  # -------------- AI SERVICE -------------------
  ai-service:
    image: rabbitly-ai-service:prod
    container_name: ai-service
    build:
      context: ./ai-service
      target: prod
    ports:
      - "9000:9000"
    environment:
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - qdrant
    restart: always

  # ------------- CODE‑RUNNER --------------------
  code-runner:
    image: rabbitly-code-runner:prod
    container_name: code-runner
    build:
      context: ./code-runner
      target: prod
    ports:
      - "9100:9100"
    restart: always

  # ------------- VECTOR DB (Qdrant) -------------
  qdrant:
    image: qdrant/qdrant:v1.8.7
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    restart: always
